#!/usr/bin/env swift
//
// render-logo.swift
//
// Deterministic generator for the macssential README/logo artwork:
// the same 6-spoke geometric asterisk (✱) as the menu bar icon —
// 3 crossing rounded capsules — rendered at 512x512 in neutral gray.
//
// Usage:
//   swift scripts/render-logo.swift
//
// Emits:
//   docs/assets/logo.png  (512x512, #8E8E93 on transparent)
//
// The single gray variant is legible on both GitHub light (white) and
// dark (near-black) backgrounds, so no <picture>/dark-variant is needed.

import AppKit
import ImageIO
import UniformTypeIdentifiers

// MARK: - Design parameters (22pt design space — identical to render-menubar-icon.swift)

let canvasSize: CGFloat = 22.0        // pt — design space
let markLength: CGFloat = 16.0        // pt — capsule length (>= 3pt margin on all sides)
let markThickness: CGFloat = 2.6      // pt — capsule thickness
let spokeAngles: [CGFloat] = [0, 60, 120].map { $0 * .pi / 180 }  // vertical + 60° + 120°

let outputPixels = 512                // px — logo output size

let center = CGPoint(x: canvasSize / 2, y: canvasSize / 2)

// MARK: - Geometry

/// Vertical capsule centered at `center`: fully-rounded rect spanning
/// y in [center.y - length/2, center.y + length/2], width = thickness.
func capsulePath() -> CGPath {
    let rect = CGRect(
        x: center.x - markThickness / 2,
        y: center.y - markLength / 2,
        width: markThickness,
        height: markLength
    )
    return CGPath(
        roundedRect: rect,
        cornerWidth: markThickness / 2,
        cornerHeight: markThickness / 2,
        transform: nil
    )
}

// MARK: - Rendering

func renderLogo() -> CGImage {
    guard let context = CGContext(
        data: nil,
        width: outputPixels,
        height: outputPixels,
        bitsPerComponent: 8,
        bytesPerRow: 0,
        space: CGColorSpace(name: CGColorSpace.sRGB)!,
        bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue
    ) else {
        fatalError("Failed to create CGContext for \(outputPixels)x\(outputPixels)")
    }

    context.setShouldAntialias(true)
    // Non-integer scale mapping the 22pt design space onto the 512px canvas.
    let scale = CGFloat(outputPixels) / canvasSize
    context.scaleBy(x: scale, y: scale)
    // Neutral gray #8E8E93 (Apple systemGray) — legible on light and dark.
    context.setFillColor(
        CGColor(red: 0x8E / 255.0, green: 0x8E / 255.0, blue: 0x93 / 255.0, alpha: 1)
    )

    let capsule = capsulePath()
    for angle in spokeAngles {
        context.saveGState()
        // Rotate about the canvas center: translate → rotate → translate back.
        context.translateBy(x: center.x, y: center.y)
        context.rotate(by: angle)
        context.translateBy(x: -center.x, y: -center.y)
        context.addPath(capsule)
        context.fillPath()
        context.restoreGState()
    }

    guard let image = context.makeImage() else {
        fatalError("Failed to make CGImage for logo")
    }
    return image
}

// MARK: - PNG output

/// Deterministic provenance note embedded as a PNG tEXt Description chunk.
let provenanceNote = """
macssential logo — 6-spoke geometric asterisk (three crossing rounded \
capsules, 16pt length, 2.6pt thickness, 22pt design space), 512x512, \
#8E8E93 on transparent. Generated by scripts/render-logo.swift; do not \
hand-edit — re-run to regenerate.
"""

func writePNG(_ image: CGImage, to url: URL) {
    guard let destination = CGImageDestinationCreateWithURL(
        url as CFURL, UTType.png.identifier as CFString, 1, nil
    ) else {
        fatalError("Failed to create PNG destination at \(url.path)")
    }
    let properties: [CFString: Any] = [
        kCGImagePropertyPNGDictionary: [
            kCGImagePropertyPNGDescription: provenanceNote
        ]
    ]
    CGImageDestinationAddImage(destination, image, properties as CFDictionary)
    guard CGImageDestinationFinalize(destination) else {
        fatalError("Failed to write PNG at \(url.path)")
    }
}

// MARK: - Sanity metric

/// Ratio of pixels with alpha above `threshold` over total pixels.
/// threshold 0 → any coverage (includes anti-aliased fringe);
/// threshold 127 → solid pixels only (closer to geometric coverage).
func filledPixelRatio(of image: CGImage, alphaAbove threshold: UInt8 = 0) -> Double {
    let width = image.width
    let height = image.height
    guard let context = CGContext(
        data: nil,
        width: width,
        height: height,
        bitsPerComponent: 8,
        bytesPerRow: width * 4,
        space: CGColorSpace(name: CGColorSpace.sRGB)!,
        bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue
    ) else { return 0 }
    context.draw(image, in: CGRect(x: 0, y: 0, width: width, height: height))
    guard let data = context.data else { return 0 }
    let buffer = data.bindMemory(to: UInt8.self, capacity: width * height * 4)
    var filled = 0
    for i in 0..<(width * height) where buffer[i * 4 + 3] > threshold {
        filled += 1
    }
    return Double(filled) / Double(width * height)
}

// MARK: - Main

let scriptURL = URL(fileURLWithPath: CommandLine.arguments[0])
// scripts/render-logo.swift → repo root is the script's parent's parent.
let repoRoot = scriptURL.deletingLastPathComponent().deletingLastPathComponent()
let assetsURL = repoRoot.appendingPathComponent("docs/assets")

try FileManager.default.createDirectory(
    at: assetsURL, withIntermediateDirectories: true
)

let image = renderLogo()
let outputURL = assetsURL.appendingPathComponent("logo.png")
writePNG(image, to: outputURL)
let anyCoverage = filledPixelRatio(of: image)
let solid = filledPixelRatio(of: image, alphaAbove: 127)
print(String(
    format: "logo.png — %dx%d px, filled-pixel ratio: %.3f (alpha>0), %.3f (solid)",
    image.width, image.height, anyCoverage, solid
))
